### PR TITLE
Functions-Theory Added

### PR DESCRIPTION
**Pull request by reallyinvincible**

### CODE REVIEW

**Comment by pranav1601** [comment]
Hey @reallyinvincible ,
adding some reference links to the document would be better and also add examples to the examples folder as discussed earlier.

**Comment by reallyinvincible** [comment]
@pranav1601 
Necessary changes have been made.

**Comment by akshitgrover** [comment]
@reallyinvincible 
Rename function_scope file to function_scope.py
Also, Reduce down the number of commits, Combine all the example file commits to one commit "Add function examples", Do the same for readme with commit message "Update functions file"

**Comment by reallyinvincible** [comment]
@akshitgrover
File has been renamed. 
It isn't possible to make all those commits into a single commit since whatever commits I make next will also include all those previous commits.
I don't think number of commits will be an issue.

**Pull request closed without merging**
